"""Create recycling events table

Revision ID: 6d4fe7e53b4e
Revises: 
Create Date: 2026-08-09 03:47:27.316824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4fe7e53b4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recycling_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.String(length=100), nullable=False),
    sa.Column('material_type', sa.String(length=50), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('estimated_weight_kg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("processing_status IN ('received', 'processed', 'failed')", name='check_processing_status'),
    sa.CheckConstraint('item_count > 0', name='check_item_count_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recycling_events')
    # ### end Alembic commands ###
